In [ ]:

import numpy as np

# Define the transition matrix T
T = np.array([[0.99, 0.2], [0.01, 0.8]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(T)

# Print the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues: [1.   0.79]
Eigenvectors:
[[ 0.99875234 -0.70710678]
 [ 0.04993762  0.70710678]]


In [ ]:

# Define the prior probability (initial belief) of getting heads
prior_probability_heads = 0.5

# Define the likelihood of getting heads (in this case, 0.5 since it's a fair coin)
likelihood_heads = 0.5

# Perform 7 consecutive tosses with all heads
num_tosses = 7
for _ in range(num_tosses):
    # Calculate the posterior probability using Bayes' theorem
    posterior_probability_heads = (prior_probability_heads * likelihood_heads) / ((prior_probability_heads * likelihood_heads) + ((1 - prior_probability_heads) * (1 - likelihood_heads)))

    # Update the prior probability for the next toss
    prior_probability_heads = posterior_probability_heads

print(f"The posterior probability of getting heads after 7 consecutive heads is: {posterior_probability_heads:.4f}")

The posterior probability of getting heads after 7 consecutive heads is: 0.5000


In [ ]:

# Define the prior probability of getting heads (initial belief that the coin is fair)
prior_probability = 0.5

# Define the number of tosses
num_tosses = 7

# List to store the posterior probabilities after each toss
posterior_probabilities = []

for _ in range(num_tosses):
    # Likelihood: Probability of getting heads (assuming the coin is fair, it's 0.5)
    likelihood = 0.5

    # Update the posterior probability using Bayes' theorem
    posterior_probability = (prior_probability * likelihood) / (prior_probability * likelihood + (1 - prior_probability) * (1 - likelihood))

    # Update the prior probability for the next toss
    prior_probability = posterior_probability

    # Append the posterior probability to the list
    posterior_probabilities.append(posterior_probability)

# The final posterior probability after 7 consecutive heads is the result
final_posterior_probability = posterior_probabilities[-1]

print("Final posterior probability after 7 consecutive heads:", final_posterior_probability)

Final posterior probability after 7 consecutive heads: 0.5


In [ ]:

def display_penguins(n):
    penguin = [
        "   _~_   ",
        "  (o o)  ",
        " /  V  \\ ",
        "/(  _  )\\",
        "  ^^ ^^  "
    ]
    for i in range(len(penguin)):
        for j in range(n):
            print(penguin[i], end=" ")
        print()


if __name__ == "__main__":
    try:
        N = int(input("Enter a natural number (1 to 9): "))
        if 1 <= N <= 9:
            display_penguins(N)
        else:
            print("Please enter a natural number between 1 and 9.")
    except ValueError:
        print("Invalid input. Please enter a valid natural number.")

Enter a natural number (1 to 9): 3
   _~_       _~_       _~_    
  (o o)     (o o)     (o o)   
 /  V  \   /  V  \   /  V  \  
/(  _  )\ /(  _  )\ /(  _  )\ 
  ^^ ^^     ^^ ^^     ^^ ^^   


In [2]:

import numpy as np
import sympy

# Given matrix A
A = np.array([[5, -6, -6],
              [-1, 4, 2],
              [3, -6, -4]])

# Step 1: Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Step 2: Form matrix P with eigenvectors as columns
P = eigenvectors

# Step 3: Calculate the inverse of P
P_inv = np.linalg.inv(P)

# Step 4: Diagonal matrix D
D = np.diag(eigenvalues)

# Step 5: Verify A = P * D * P_inv
reconstructed_A = P @ D @ P_inv

Alternate = sympy.Matrix(A).diagonalize()

# Print results
print("Original Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (as columns):")
print(eigenvectors)
print("\nMatrix P:")
print(P)
print("\nMatrix P inverse:")
print(P_inv)
print("\nDiagonal Matrix D:")
print(D)
print("\nReconstructed A (should be equal to original A):")
print(reconstructed_A)
print("\nDiagonalize using sympy library")
print(Alternate)

Original Matrix A:
[[ 5 -6 -6]
 [-1  4  2]
 [ 3 -6 -4]]

Eigenvalues:
[1. 2. 2.]

Eigenvectors (as columns):
[[-0.6882472  -0.68543457 -0.94146641]
 [ 0.22941573  0.31415751 -0.19764316]
 [-0.6882472  -0.6568748  -0.27309005]]

Matrix P:
[[-0.6882472  -0.68543457 -0.94146641]
 [ 0.22941573  0.31415751 -0.19764316]
 [-0.6882472  -0.6568748  -0.27309005]]

Matrix P inverse:
[[ 4.35889894 -8.71779789 -8.71779789]
 [-4.01641369  9.29936073  7.1162006 ]
 [-1.32454135 -0.3973624   1.19208721]]

Diagonal Matrix D:
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

Reconstructed A (should be equal to original A):
[[ 5. -6. -6.]
 [-1.  4.  2.]
 [ 3. -6. -4.]]

Diagonalize using sympy library
(Matrix([
[ 3, 2, 2],
[-1, 1, 0],
[ 3, 0, 1]]), Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 2]]))


In [4]:

from sympy import Matrix

# Define your 3x3 matrix as a Sympy Matrix
matrix = Matrix([[5, -6, -6],
                 [-1, 4, 2],
                 [3, -6, -4]])

# Find eigenvalues and eigenvectors
eigeninfo = matrix.eigenvects()

# Extract eigenvalues and eigenvectors from the result
eigenvalues = [ei[0] for ei in eigeninfo]
eigenvectors = [ei[2][0] for ei in eigeninfo]

# Print the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i, vector in enumerate(eigenvectors):
    print(f"Eigenvalue {i + 1}: {vector}")

Eigenvalues: [1, 2]
Eigenvectors:
Eigenvalue 1: Matrix([[1], [-1/3], [1]])
Eigenvalue 2: Matrix([[2], [1], [0]])


In [5]:

import numpy as np

# Define your 3x3 matrix
matrix = np.array([[5, -6, -6],
                   [-1, 4, 2],
                   [3, -6, -4]])

# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues: [1. 2. 2.]
Eigenvectors:
[[-0.6882472  -0.68543457 -0.94146641]
 [ 0.22941573  0.31415751 -0.19764316]
 [-0.6882472  -0.6568748  -0.27309005]]
